FROM python:3.12-slim

RUN apt-get update && apt-get install -y redis-server && rm -rf /var/lib/apt/lists/*

WORKDIR /gameserver

COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt

RUN chmod +x server.sh

EXPOSE 6379 8000

CMD [ "./server.sh" ]
